//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fi.retorch.com.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int TypeId { get; set; }
        public string Name { get; set; }
        public System.DateTime DateOpened { get; set; }
        public decimal OpeningBalance { get; set; }
        public decimal CurrentBalance { get; set; }
        public bool IsClosed { get; set; }
        public bool IsDisplayed { get; set; }
        public int DisplayOrder { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
    }
}
