//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fi.retorch.com.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class act_categories
    {
        public int category_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> account_id { get; set; }
        public string category_name { get; set; }
        public byte isActive { get; set; }
    }
}
