//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fi.retorch.com.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class act_transactions
    {
        public int transaction_id { get; set; }
        public Nullable<int> account_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> smt_id { get; set; }
        public string transaction_name { get; set; }
        public Nullable<System.DateTime> transaction_date { get; set; }
        public Nullable<int> amount { get; set; }
        public byte positive { get; set; }
        public byte registered { get; set; }
        public Nullable<System.DateTime> register_date { get; set; }
    
        public virtual act_accounts act_accounts { get; set; }
    }
}
