//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fi.retorch.com.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookmark
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string URL { get; set; }
        public string Text { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
