//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fi.retorch.com.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LegacyEntities : DbContext
    {
        public LegacyEntities()
            : base("name=LegacyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<act_account_categories> act_account_categories { get; set; }
        public virtual DbSet<act_accounts> act_accounts { get; set; }
        public virtual DbSet<act_categories> act_categories { get; set; }
        public virtual DbSet<act_reminders> act_reminders { get; set; }
        public virtual DbSet<act_schedules> act_schedules { get; set; }
        public virtual DbSet<act_transactions> act_transactions { get; set; }
        public virtual DbSet<act_types> act_types { get; set; }
        public virtual DbSet<ng_users> ng_users { get; set; }
        public virtual DbSet<act_links> act_links { get; set; }
    }
}
