//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fi.retorch.com.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ng_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ng_users()
        {
            this.act_accounts = new HashSet<act_accounts>();
            this.act_links = new HashSet<act_links>();
        }
    
        public int user_id { get; set; }
        public System.DateTime time_stamp { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string display { get; set; }
        public string email { get; set; }
        public string signature { get; set; }
        public System.Guid rss_password { get; set; }
        public Nullable<int> current_list { get; set; }
        public int option_clear { get; set; }
        public string bdy_coord { get; set; }
        public bool locked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<act_accounts> act_accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<act_links> act_links { get; set; }
    }
}
