//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fi.retorch.com.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public int ScheduleId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public bool IsCredit { get; set; }
        public System.DateTime NextDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public int Sequence { get; set; }
    }
}
